plugins {
    id 'buildlogic.java-common-conventions'
    id 'org.jetbrains.intellij.platform'
}

repositories {
    intellijPlatform {
        defaultRepositories()
        jetbrainsRuntime()
    }
}

import org.jetbrains.intellij.platform.gradle.TestFrameworkType

dependencies {
    intellijPlatform {
        intellijIdeaCommunity '2025.2'
        jetbrainsRuntime()

        //bundledPlugin 'com.intellij.java'

        pluginVerifier()
        zipSigner()
        instrumentationTools()

        testFramework TestFrameworkType.Platform.INSTANCE
    }
}


Properties props = new Properties()
try (FileInputStream fis = new FileInputStream(new File(parent.rootDir.getPath(), 'application.properties'))) {
    props.load(fis)
}

patchPluginXml {
    sinceBuild = props.getProperty('sinceBuild')
    untilBuild = props.getProperty('untilBuild')
}

intellijPlatform {
    autoReload = true
}

buildSearchableOptions {
    enabled = false
}

tasks.withType(org.gradle.jvm.tasks.Jar).configureEach {
    archiveBaseName = props.getProperty('artifactId')
}

tasks.named('buildPlugin') {
    dependsOn(processResources)
}

tasks.processResources {
    doLast {
        String txt = file("build/resources/main/META-INF/plugin.xml").text
        txt = txt.replace('${name}', props.getProperty('name'))
            .replace('${version}', props.getProperty('version'))
            .replace('${url}', props.getProperty('url'))
            .replace('${vendor}', props.getProperty('vendor'))
            .replace('${sinceBuild}', props.getProperty('sinceBuild'))
            .replace('${untilBuild}', props.getProperty('untilBuild'))

        file("build/resources/main/META-INF/plugin.xml").write(txt)
    }
}
